### ISSUE TITLE
[Feature request] Playback speed control

### ISSUE THREAD

**Issue by Vitamin-B** [RomanTsarou/XPlayer#1]
Hi, I tried to implement playback speed control into XPlayer via sendCommand, but could not find where to override onCommand and how to link it to exoPlayer, thus I would appreciate that feature or at least some directions for implementing it :)
Thank you very much for your time.

**Comment by Vitamin-B** [comment]
Oh, I found onCommand in UampPlaybackPreparer. I somehow missed it.
So just to answer my own question if someone else might stomp upon similar problem:
What is needed is to add
`fun setSpeed(speed : Float)` to `IPlayer`
`override fun setSpeed(speed : Float) = playerImpl.setSpeed(speed)` to `Player`

    override fun setSpeed(speed: Float) {
        val bundle = Bundle()
        bundle.putFloat("speed", speed)
        mediaController?.sendCommand("speed",bundle, null)
    }

to `PlayerImpl` and update the `getCommands()` and `onCommands()` functions in `UampPlaybackPreparer.kt`

    override fun getCommands(): Array<String>? = arrayOf("speed")

    override fun onCommand(
        player: Player?,
        command: String?,
        extras: Bundle?,
        cb: ResultReceiver?
    ) {
        when (command) {
            "speed" -> {
                setSpeed(extras!!.getFloat("speed"))
            }
        }
    }

    private fun setSpeed(speed: Float) {
        val param = PlaybackParameters(speed)
        exoPlayer.playbackParameters = param
    }

**Comment by RomanTsarou** [comment]
I added speed parameter to player 0.0.4
Thanks for your hint
